CREATE DATABASE QUANLYBANHANG;
USE QUANLYBANHANG;
CREATE TABLE CUSTOMER(
CID INT NOT NULL PRIMARY KEY auto_increment,
CNAME VARCHAR(50) NOT NULL,
CAGE INT CHECK(CAGE >=18)
);
CREATE TABLE ORDERLIST(
OID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CID INT NOT NULL,
ODATE DATETIME NOT NULL,
OTOTALPRICE DOUBLE CHECK(OTOTALPRICE > 0)
);
CREATE TABLE PRODUCT (
PID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
PNAME VARCHAR(50) NOT NULL,
PPRICE DOUBLE CHECK(PPRICE > 0)
);
CREATE TABLE ORDERDETAIL(
OID INT NOT NULL,
PID INT NOT NULL,
ODQTY DOUBLE,
PRIMARY KEY(OID,PID),
foreign key (OID) references ORDERLIST(OID),
foreign key (PID) references PRODUCT(PID)
);
alter TABLE ORDERLIST ADD foreign key (CID) references CUSTOMER(CID);